### ISSUE TITLE
step within spec not found

### ISSUE THREAD

**Issue by dynamicworkplace** [simplybusiness/rutabaga#11]
I'm experiencing a problem when running the `rspec` command without specifying the folder - my (request) spec which includes a feature is reported as pending. The pending step is defined within the spec itself. If I run `rspec spec/features` then the tests pass without any problems.

I'd be grateful for your advice.

Thank you
Dan

**Comment by lukaso** [comment]
@dynamicworkplace Sorry, i didn't see this message.

Where have you located the spec. Is this in the `spec/features` directory? Could you provide me with a brief overview of the files, locations and the call to the feature.

Again, sorry about the delay of seeing this.

**Comment by dynamicworkplace** [comment]
@lukaso Yes, the `test.feature` and `test_spec.rb` and both in `spec/features` (there is also a `spec/features/steps/common_steps.rb`). The steps that are being reported as not defined are in the `test_spec.rb` file within a `describe` block (describing a feature rather than the `Rspec.describe` outer block).

**Comment by lukaso** [comment]
OK. That makes total sense. 

When you are using rutabaga style tests, these cannot live in the `spec/features` directory. Anywhere else under `spec` will work. I've left `spec/features` (and any subdirectories) for turnip style tests and common steps.

Move `test.feature` and `test_spec.rb` to the `spec` directory, (or any other directory outside of `spec/features`), then run `bundle exec rspec -r rutabaga spec/test_spec.rb` and all should work.

**Comment by lukaso** [comment]
@dynamicworkplace I've now added a feature which allows you to completely disable turnip style features. This is described here #15 and here https://github.com/simplybusiness/rutabaga/blob/master/README.md and is available in v2.1.1.
